server:
  address: localhost
  port: 9090

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/authorization
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true
        "[user_sql_comments]": true
        "[highlight_sql]": true
        "[hbm2ddl.auto]": create
    open-in-view: true
    show-sql: true
  mvc:
    log-request-details: true



  security:
    oauth2:
      authorization-server:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  security:
    oauth2:
      authorization-server:
        client:
          oidc-client:
            registration:
              client-id: "demo-client"
              client-secret: "demo-client-secret"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:9191/login/oauth2/code/demo-client-oidc"
                - "http://127.0.0.1:9191/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:9191/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true

logging:
  level:
    root: INFO
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: trace





