server:
  port: 8989

logging:
  level:
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/authorization
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true
        "[user_sql_comments]": true
        "[highlight_sql]": true
        "[hbm2ddl.auto]": update
    open-in-view: true
    show-sql: true

  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
